Improving module content
griffinfoster/fundamentals_of_interferometry pull request #113
Opened 2024-11-08 15:08 UTC by astromancer

Khutso suggested that I go through this module to prep for the upcoming Africalim workshop etc. I've noticed a few typos and mistakes in the math, so I'm opening this to correct those as I discover them. I've also addressed some of the contributor comments in the notebooks.  Will keep this as a draft for now until I work my way through all the sections.

2024-12-18 11:39 UTC, o-smirnov requested changes
Thanks very much @astromancer, this is a massive amount of work an extremely valuable update! I've picked up a couple of typos noted above? Could you please fix, and I'll merge.

2024-12-18 11:39 UTC, o-smirnov commented on 1_Radio_Science/1_5_black_body_radiation.ipynb
> +    "n radio astronomy, a more typical situation is when the frequency of the radiation is so low that $h\\nu << kT$. In this case the Planck formula can be approximated by the Rayleigh-Jeans formula
Typo n -> in?

2024-12-18 11:39 UTC, o-smirnov commented on 1_Radio_Science/1_8_astronomical_radio_sources.ipynb
> +    "The emission from the \"quiet sun\" is a mixture of thermal and non-thermal emission. However, the strongest radio emission from the sun comes from coronal mass ejections and solar flares. The f
sun -> Sun

2024-12-18 11:39 UTC, o-smirnov commented on 1_Radio_Science/1_9_a_brief_introduction_to_interferometry.ipynb
> +    "Firstly, a monochromatic electromagnetic wave of wavelength $\\lambda$ can be described at each point in time and space as a complex quantity i.e. having an amplitude $A$, and a phase $\\phi$, s
such that -> i.e.?

2025-01-07 10:12 UTC, Athanaseus reviewed
Minor suggestions

2025-01-07 10:12 UTC, Athanaseus commented on 0_Introduction/1_glossary.ipynb
> +    "* Planck constant: $h = 6.62607015 \\times 10^{−34}\\ \\mathrm{J\\, Hz^{−1}}$"
Use standard hyphen in exponents over Unicode minus:

```suggestion
    "* Planck constant: $h = 6.62607015 \\times 10^{-34}\\ \\mathrm{J\\, Hz^{-1}}$"
```

2025-01-07 10:12 UTC, Athanaseus commented on 0_Introduction/1_glossary.ipynb
> +    "* $L$: Bolometric Luminosity (W/s, ergs/s)\n",
```suggestion
    "* $L$: Bolometric Luminosity ($\mathrm{W}$ or $\mathrm{erg\,s^{-1}}$)\n",
```

2025-01-07 11:21 UTC, bennahugo commented on 1_Radio_Science/1_3_radiative_transport.ipynb
> +    "Here $\\kappa_\\nu(x)$ is called the linear absorption coefficient. Furthermore, intensity will be *generated* independently of the incoming radiation in such a way that the intensity will incre
depend on $x$

2025-01-07 11:50 UTC, bennahugo commented on 1_Radio_Science/1_11_modern_interferometric_arrays.ipynb
> +    "The MeerKAT array consist of 64 dishes, with a shortest baseline similar to KAT-7, but with a maximum baseline of 8 km! This allows for high resolution measurements up to 6.6 arc-second.\n",
arcsecond

2025-01-07 12:16 UTC, bennahugo requested changes
Minor changes

2025-01-07 15:55 UTC, bennahugo approved these changes

2025-01-07 16:01 UTC, merged